
    create table categoria (
       id int8 generated by default as identity,
        descricao varchar(255),
        img varchar(255),
        nome varchar(255),
        obs varchar(255),
        status boolean,
        empresa_id int8,
        primary key (id)
    );

    create table cidade (
       id int8 generated by default as identity,
        dt_cadastro date,
        nome varchar(255),
        obs varchar(255),
        uf varchar(255),
        primary key (id)
    );

    create table consumidor (
       id int8 generated by default as identity,
        bairro varchar(255),
        dt_cadastro date,
        email varchar(255),
        endereco varchar(255),
        fone1 varchar(255),
        fone2 varchar(255),
        img varchar(255),
        login varchar(255),
        nome varchar(255),
        obs varchar(255),
        senha varchar(255),
        status boolean,
        cidade_id int8,
        primary key (id)
    );

    create table empresa (
       id int8 generated by default as identity,
        bairro varchar(255),
        cpf_cnpj varchar(255),
        dt_cadastro date,
        email varchar(255),
        endereco varchar(255),
        fone1 varchar(255),
        fone2 varchar(255),
        img varchar(255),
        nome varchar(255),
        obs varchar(255),
        status boolean,
        cidade_id int8,
        primary key (id)
    );

    create table produto (
       id int8 generated by default as identity,
        descricao varchar(255),
        dt_cadastro date,
        img varchar(255),
        nome varchar(255),
        obs varchar(255),
        preco float8,
        status boolean,
        categoria_id int8,
        primary key (id)
    );

    create table usuario (
       id int8 generated by default as identity,
        dt_cadastro date,
        email varchar(255),
        fone1 varchar(255),
        fone2 varchar(255),
        img varchar(255),
        login varchar(255),
        nivel varchar(255),
        nome varchar(255),
        obs varchar(255),
        senha varchar(255),
        status boolean,
        empresa_id int8,
        primary key (id)
    );

    alter table if exists categoria 
       add constraint FKph8u7xb0x8axyrppb6gx47766 
       foreign key (empresa_id) 
       references empresa;

    alter table if exists consumidor 
       add constraint FKaagmnah342w76gcc1y710ofvl 
       foreign key (cidade_id) 
       references cidade;

    alter table if exists empresa 
       add constraint FKmwu5vrlfrn44ja26d5h4tcodh 
       foreign key (cidade_id) 
       references cidade;

    alter table if exists produto 
       add constraint FKopu9jggwnamfv0c8k2ri3kx0a 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists usuario 
       add constraint FK87ckfs30l64gnivnfk7ywp8l6 
       foreign key (empresa_id) 
       references empresa;
